name: recipe
description: Implementation and parser of BakeCode Recipe.
version: 0.0.1-alpha
repository: https://github.com/bakecode-devs/recipe

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  json_annotation: ^4.0.1
  checked_yaml: ^2.0.1
  async: ^2.5.0
  equatable: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
