name: recipe
description: Implementation and parser of BakeCode Recipe.
version: 0.0.1-alpha
repository: https://github.com/bakecode-devs/recipe

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  json_annotation: ^4.1.0
  checked_yaml: ^2.0.1
  fhir_yaml: ^0.5.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
